version: '3.8'
services:
  app:
    container_name: mongodb-nodejs
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules  
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${ENV_MONGO_URL}

  mongo:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  mongo_data: